### ISSUE TITLE
바인딩 체크박스 문제

### ISSUE THREAD

**Issue by jsw418jj** [ax5ui/ax5ui-binder#1]
우선 이 문의를 여기에 작성해도 되는지 모르겠네요..

제가 문의할려는 내용은 데모페이지에서 사용자관리 패스워드 변경 체크박스 입니다.
전 처음 페이지가 로딩될때 체크박스가 체크가 되고 readonly는 제거를 한상태로 만들려고 하는데..

this.target.find('[data-ax-path="password_change"]').attr("checked",true); 
이렇게 옵션을 줘도 체크박스 체크가 되지 않습니다.
input 태그에는 checked 속성은 들어가져 있고요

jsp에서 input 태그 자체에 checked="checked"를 넣어서 refresh를 하니 처음에는 체크가 되어 있다 마스크가 없어지면서 체크가 풀려 버립니다.

data-ax-path 속성을 사용하지 않으면 체크박스 체크는 잘되는데 이 속성이 어디에서 풀리게 만드는지 체크가 안되네요.

어떻게 처리를 해야 하나요??

**Comment by thomasJang** [comment]
data-ax-path 를 사용하면 

`this.model.setModel(this.getDefaultData(), this.target);`
에서 폼의 폼컨트롤 요소들의 값과 상태를 오브젝트 키로 값을 모두 변경 시켜 줍니다.

setModel 처리 후에 체크값을 변경하고 trigger("change") 하거나.
setModel에 전달할 오브젝트에 해당 키 값을 주면 알아서 체크된 체로 폼이 뿌려집니다.

http://ax5.io/ax5ui-binder/demo/index.html 여기 예제코드를 보면 이해가 되 실 것 같습니다.

**Comment by jsw418jj** [comment]
감사합니다.
잘 처리 했습니다, 
jquery 를 사용하면 될꺼라 생각했는데 model 에 set해서 사용하는것을 생각을 못했네요 ㅎㅎ
